# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='hft.common',
  syntax='proto3',
  serialized_options=b'\252\002\030Lykke.HftApi.ApiContract',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63ommon.proto\x12\nhft.common\"\x9b\x01\n\x05\x45rror\x12#\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x15.hft.common.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12-\n\x06\x66ields\x18\x03 \x03(\x0b\x32\x1d.hft.common.Error.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\x94\x05\n\tErrorCode\x12\x0b\n\x07success\x10\x00\x12\x11\n\x0cruntimeError\x10\xe9\x07\x12\x11\n\x0citemNotFound\x10\xcc\x08\x12\x11\n\x0cinvalidField\x10\xcd\x08\x12\x14\n\x0f\x61\x63tionForbidden\x10\xce\x08\x12\x11\n\x0cmeBadRequest\x10\xd0\x0f\x12\x11\n\x0cmeLowBalance\x10\xd1\x0f\x12\x17\n\x12meAlreadyProcessed\x10\xd2\x0f\x12\x14\n\x0fmeDisabledAsset\x10\xd3\x0f\x12\x13\n\x0emeUnknownAsset\x10\xd4\x0f\x12\x12\n\rmeNoLiquidity\x10\xd5\x0f\x12\x15\n\x10meNotEnoughFunds\x10\xd6\x0f\x12\x0b\n\x06meDust\x10\xd7\x0f\x12&\n!meReservedVolumeHigherThanBalance\x10\xd8\x0f\x12\x0f\n\nmeNotFound\x10\xd9\x0f\x12\x1f\n\x1ameBalanceLowerThanReserved\x10\xda\x0f\x12\x1b\n\x16meLeadToNegativeSpread\x10\xdb\x0f\x12\x15\n\x10meTooSmallVolume\x10\xdc\x0f\x12\x11\n\x0cmeInvalidFee\x10\xdd\x0f\x12\x13\n\x0emeInvalidPrice\x10\xde\x0f\x12\x0f\n\nmeReplaced\x10\xdf\x0f\x12\x17\n\x12meNotFoundPrevious\x10\xe0\x0f\x12\x10\n\x0bmeDuplicate\x10\xe1\x0f\x12\x1c\n\x17meInvalidVolumeAccuracy\x10\xe2\x0f\x12\x1b\n\x16meInvalidPriceAccuracy\x10\xe3\x0f\x12\x14\n\x0fmeInvalidVolume\x10\xe4\x0f\x12\x1c\n\x17meTooHighPriceDeviation\x10\xe5\x0f\x12\x18\n\x13meInvalidOrderValue\x10\xe6\x0f\x12\x0e\n\tmeRuntime\x10\xe7\x0f\x42\x1b\xaa\x02\x18Lykke.HftApi.ApiContractb\x06proto3'
)

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='hft.common.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='success', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='runtimeError', index=1, number=1001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='itemNotFound', index=2, number=1100,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='invalidField', index=3, number=1101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='actionForbidden', index=4, number=1102,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meBadRequest', index=5, number=2000,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meLowBalance', index=6, number=2001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meAlreadyProcessed', index=7, number=2002,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meDisabledAsset', index=8, number=2003,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meUnknownAsset', index=9, number=2004,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meNoLiquidity', index=10, number=2005,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meNotEnoughFunds', index=11, number=2006,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meDust', index=12, number=2007,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meReservedVolumeHigherThanBalance', index=13, number=2008,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meNotFound', index=14, number=2009,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meBalanceLowerThanReserved', index=15, number=2010,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meLeadToNegativeSpread', index=16, number=2011,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meTooSmallVolume', index=17, number=2012,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meInvalidFee', index=18, number=2013,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meInvalidPrice', index=19, number=2014,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meReplaced', index=20, number=2015,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meNotFoundPrevious', index=21, number=2016,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meDuplicate', index=22, number=2017,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meInvalidVolumeAccuracy', index=23, number=2018,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meInvalidPriceAccuracy', index=24, number=2019,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meInvalidVolume', index=25, number=2020,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meTooHighPriceDeviation', index=26, number=2021,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meInvalidOrderValue', index=27, number=2022,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='meRuntime', index=28, number=2023,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=187,
  serialized_end=847,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
success = 0
runtimeError = 1001
itemNotFound = 1100
invalidField = 1101
actionForbidden = 1102
meBadRequest = 2000
meLowBalance = 2001
meAlreadyProcessed = 2002
meDisabledAsset = 2003
meUnknownAsset = 2004
meNoLiquidity = 2005
meNotEnoughFunds = 2006
meDust = 2007
meReservedVolumeHigherThanBalance = 2008
meNotFound = 2009
meBalanceLowerThanReserved = 2010
meLeadToNegativeSpread = 2011
meTooSmallVolume = 2012
meInvalidFee = 2013
meInvalidPrice = 2014
meReplaced = 2015
meNotFoundPrevious = 2016
meDuplicate = 2017
meInvalidVolumeAccuracy = 2018
meInvalidPriceAccuracy = 2019
meInvalidVolume = 2020
meTooHighPriceDeviation = 2021
meInvalidOrderValue = 2022
meRuntime = 2023



_ERROR_FIELDSENTRY = _descriptor.Descriptor(
  name='FieldsEntry',
  full_name='hft.common.Error.FieldsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='hft.common.Error.FieldsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='hft.common.Error.FieldsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=184,
)

_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='hft.common.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='hft.common.Error.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='hft.common.Error.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fields', full_name='hft.common.Error.fields', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ERROR_FIELDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=184,
)

_ERROR_FIELDSENTRY.containing_type = _ERROR
_ERROR.fields_by_name['code'].enum_type = _ERRORCODE
_ERROR.fields_by_name['fields'].message_type = _ERROR_FIELDSENTRY
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {

  'FieldsEntry' : _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ERROR_FIELDSENTRY,
    '__module__' : 'common_pb2'
    # @@protoc_insertion_point(class_scope:hft.common.Error.FieldsEntry)
    })
  ,
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:hft.common.Error)
  })
_sym_db.RegisterMessage(Error)
_sym_db.RegisterMessage(Error.FieldsEntry)


DESCRIPTOR._options = None
_ERROR_FIELDSENTRY._options = None
# @@protoc_insertion_point(module_scope)
